let twitterContent = [
  {
    id: 1,
    url: 'https://www.youtube.com/watch?v=XHHtNFaNCJo',
    title: 'Imagination - Instinctual (David Morales Remix)',
    year: '1987',
  },
  {
    id: 2,
    url: 'https://www.youtube.com/watch?v=jvB4_T_GDNs',
    title: 'Wee Papa Girl Rappers - Heat It Up (Kevin Sanderson Remix)',
    year: '1988',
  },
  {
    id: 3,
    url: 'https://www.youtube.com/watch?v=vDBeSszh8Ok',
    title: 'Eric B & Rakim - Paid In Full (The Coldcut Remix)',
    year: '1987',
  },
  {
    id: 4,
    url: 'https://www.youtube.com/watch?v=zKFRiSUtK-I',
    title: 'George Michael - Hard Day (Shep Pettibone Remix)',
    year: '1987',
  },
  {
    id: 5,
    url: 'https://www.youtube.com/watch?v=WAN8f6583pg',
    title: 'Bjork - Human Behavior (Close To Human Mix)',
    year: '1993',
  },
  {
    id: 6,
    url: 'https://www.youtube.com/watch?v=5vkRMxjvEx0',
    title: "Crystal Method - Comin' Back (Club 69's Future Mix)",
    year: '1998',
  },
  {
    id: 7,
    url: 'https://www.youtube.com/watch?v=5yNZDHCwjdc',
    title: "Garbage - When I Grow Up (Danny Tenaglia's Club Mix)",
    year: '1999',
  },
  {
    id: 8,
    url: 'https://www.youtube.com/watch?v=JJFX5DzK8x0',
    title: 'Underworld - Two Months Off (King Unique Sunspots Vocal Mix)',
    year: '2002',
  },
  {
    id: 9,
    url: 'https://www.youtube.com/watch?v=SFSl91tG5Xo',
    title: 'Filter - Hey Man Nice Shot (1/4 lb Mix)',
    year: '1995',
  },
  {
    id: 10,
    url: 'https://www.youtube.com/watch?v=tqREpyLEsn8',
    title: 'Orgy - Stitches (Cracker Mix)',
    year: '1999',
  },
  {
    id: 11,
    url: 'https://www.youtube.com/watch?v=aOFRaQ3i8qs',
    title: 'Devo - Whip It (Philip Steir Remix)',
    year: '2003',
  },
  {
    id: 12,
    url: 'https://www.youtube.com/watch?v=bOX9tvn-6JI',
    title: "The Pharcyde - Passin' Me By (Fly As Pie Mix)",
    year: '1993',
  },
  {
    id: 13,
    url: 'https://www.youtube.com/watch?v=9lB1jiv83Q0',
    title: '3rd Bass - Wordz Of Wisdom (aka III The Hardway) (Club Mix)',
    year: '1989',
  },
  {
    id: 14,
    url: 'https://www.youtube.com/watch?v=s8G5LMmLhDA',
    title: 'LL Cool J - Mama Said Knock You Out (Hot Mix - Long)',
    year: '1991',
  },
  {
    id: 15,
    url: 'https://www.youtube.com/watch?v=7LnTSV5Oe50',
    title: "Ziggy Marley & The Melody Makers - Tumblin' Down (12 Inch Remix)",
    year: '1988',
  },
  {
    id: 16,
    url: 'https://www.youtube.com/watch?v=JfKmREVDoEc',
    title: 'Peter Gabriel - Steam (Hank Shocklee & The Bomb Squad Remix)',
    year: '1992',
  },
  {
    id: 17,
    url: 'https://www.youtube.com/watch?v=bY9yhgTDP4k',
    title: 'M - Pop Muzik (Ben Liebrand Remix)',
    year: '1989',
  },
  {
    id: 18,
    url: 'https://www.youtube.com/watch?v=DI7bBHB5ZMs',
    title: 'Smashing Pumpkins - 1979 (Roli Mossiman Vocal Mix)',
    year: '1995',
  },
  {
    id: 19,
    url: 'https://www.youtube.com/watch?v=bzT0G8fOI30',
    title: 'Electronic - Disappointed (808 State Remix)',
    year: '1992',
  },
  {
    id: 20,
    url: 'https://www.youtube.com/watch?v=5rRgjvna7bk',
    title: 'Sarah McLachlan - Fear (Lunasol Remix)',
    year: '1993',
  },
  {
    id: 21,
    url: 'https://www.youtube.com/watch?v=COIl5IzVdYg',
    title: 'Portishead - Sour Times (Lot More Mix)',
    year: '1994',
  },
  {
    id: 22,
    url: 'https://www.youtube.com/watch?v=wxiZ0bDPEHM',
    title: 'Lily Allen - LDN (Warbox Remix)',
    year: '2006',
  },
  {
    id: 23,
    url: 'https://www.youtube.com/watch?v=qFaR6rV0DBU',
    title: 'Twin Hype - For Those Who Like To Groove (Club Groove Remix)',
    year: '1989',
  },
  {
    id: 24,
    url: 'https://www.youtube.com/watch?v=dceorz43MwY',
    title: 'Black Moon - I Got Cha Opin (Remix)',
    year: '1994',
  },
  {
    id: 25,
    url: 'https://www.youtube.com/watch?v=abJeoBXixsk',
    title:
      "Method Man (feat Mary J Blige) - I'll Be There For You (Puff Daddy Remix)",
    year: '1995',
  },
  {
    id: 26,
    url: 'https://www.youtube.com/watch?v=GaFRCU3lbik',
    title: 'Roger Sanchez - Turn On The Music (Axwell Remix)',
    year: '2005',
  },
  {
    id: 27,
    url: 'https://www.youtube.com/watch?v=KE2_WFoRHZk',
    title: 'Korn - A.D.I.D.A.S. (Under Pressure Mix)',
    year: '1997',
  },
  {
    id: 28,
    url: 'https://www.youtube.com/watch?v=7Bs8ZskPe3c',
    title: 'P.O.D. - Boom (Crystal Method Remix)',
    year: '2002',
  },
  {
    id: 29,
    url: 'https://www.youtube.com/watch?v=gYJJ-4dQnqw',
    title: 'Deftones - My Own Summer (Shove It) (Charlie Clouser Remix)',
    year: '1999',
  },
  {
    id: 30,
    url: 'https://www.youtube.com/watch?v=wHGTApGNwmo',
    title: 'Hayden James - Something About You (Gazzo Remix)',
    year: '2014',
  },
  {
    id: 31,
    url: 'https://www.youtube.com/watch?v=Tm2y-0a-p8s',
    title:
      'Wanklemut & Emma Louise - My Head Is A Jungle (Friend Within Remix)',
    year: '2014',
  },
  {
    id: 32,
    url: 'https://www.youtube.com/watch?v=zwubKSxpczg',
    title: "The Latin Project - Lei Lo Lai (MAW Mix B's Re-Edit)",
    year: '2003',
  },
  {
    id: 33,
    url: 'https://www.youtube.com/watch?v=QDR8GxDGq0w',
    title: 'EMF - Unbelievable (Hip Hop Mix)',
    year: '1991',
  },
  {
    id: 34,
    url: 'https://www.youtube.com/watch?v=e4PT-FSNLwY',
    title: 'Crazy Town - Butterfly (Epic Remix)',
    year: '2000',
  },
  {
    id: 35,
    url: 'https://www.youtube.com/watch?v=MZnO54HHshs',
    title: 'P Diddy & The Family - Victory (Nine Inch Nails Remix)',
    year: '1997',
  },
  {
    id: 36,
    url: 'https://www.youtube.com/watch?v=NYK7mQMnX4Y',
    title: '69 Boyz - Tootsee Roll (Set It Off Mix)',
    year: '1994',
  },
  {
    id: 37,
    url: 'https://www.youtube.com/watch?v=A5QeSl0czW0',
    title: 'C.C.C.P. - American Soviets (Cameron Paul Remix)',
    year: '1987',
  },
  {
    id: 38,
    url: 'https://www.youtube.com/watch?v=qMaYmhf87JY',
    title: 'N.E.R.D. - Lapdance (Nine Inch Nails Remix)',
    year: '',
  },
  {
    id: 39,
    url: 'https://www.youtube.com/watch?v=8n4l7UdPXIs',
    title: "Leftfield - Dusted (Si Begg's Buckfunk 3000 Remix)",
    year: '1999',
  },
  {
    id: 40,
    url: 'https://www.youtube.com/watch?v=41kXJLheSrc',
    title: 'The Prodigy - Voodoo People (Chemical Brothers Remix)',
    year: '1994',
  },
  {
    id: 41,
    url: 'https://www.youtube.com/watch?v=KWHc7rSv03Q',
    title: "The Prodigy - Everybody In The Place (Moby's Dance Hall Version)",
    year: '1992',
  },
  {
    id: 42,
    url: 'https://www.youtube.com/watch?v=Ke0RcBMDjA4',
    title: '808 State - Cubik (Kings County Perspective)',
    year: '1991',
  },
  {
    id: 43,
    url: 'https://www.youtube.com/watch?v=2ZmaJzKEJdo',
    title: "Georgio - Lover's Lane (Club Mix)",
    year: '1987',
  },
  {
    id: 44,
    url: 'https://www.youtube.com/watch?v=gJC1o35b9_s',
    title: 'INXS - Guns In The Sky (Kick Ass Remix)',
    year: '1988',
  },
  {
    id: 45,
    url: 'https://www.youtube.com/watch?v=eM5DWw3J4BI',
    title: 'Eiffel 65 - Blue (Flume Remix)',
    year: '2020',
  },
  {
    id: 46,
    url: 'https://www.youtube.com/watch?v=xYi_tbr9MMg',
    title: 'Jaydee - Plastic Dreams (David Morales Remix)',
    year: '1997',
  },
  {
    id: 47,
    url: 'https://www.youtube.com/watch?v=o2B8y5rsVSM',
    title: 'Funky Green Dogs - Fired Up (Angel Moraes ddddDeep Vocal Mix',
    year: '1996',
  },
  {
    id: 48,
    url: 'https://www.youtube.com/watch?v=4eNauLHc7Ls',
    title: 'People Underground - Music Is Pumping (Green Street Session Mix)',
    year: '1997',
  },
  {
    id: 49,
    url: 'https://www.youtube.com/watch?v=NuhJP3h31mI',
    title: 'Ella Eyre - Deeper (Friend Within Remix)',
    year: '2013',
  },
  {
    id: 50,
    url: 'https://www.youtube.com/watch?v=a0BkP5HDWj0',
    title: 'Cornershop - Brimful Of Asha (Fatboy Slim Remix)',
    year: '1997',
  },
  {
    id: 51,
    url: 'https://www.youtube.com/watch?v=mZ62ukK3y_0',
    title: "Total (feat Shyne) - Sittin' Home (Bad Boy Remix)",
    year: '1998',
  },
  {
    id: 52,
    url: 'https://www.youtube.com/watch?v=w47rwG-zSr8',
    title: "Summer Junkies - I'm Gonna Luv U (Pumped Up US Excursion)",
    year: '1997',
  },
  {
    id: 53,
    url: 'https://www.youtube.com/watch?v=1fTmwMAzwEY',
    title: 'Nalin & Kane - Beachball (DJ Icey Remix)',
    year: '1997',
  },
  {
    id: 54,
    url: 'https://www.youtube.com/watch?v=3EVZPK0Rx88',
    title: 'Public Enemy vs Benny Benassi - Bring The Noise',
    year: '2007',
  },
  {
    id: 55,
    url: 'https://www.youtube.com/watch?v=SraMud3BKAU',
    title: "CJ Bolland - Sugar Is Sweeter (Armand's Drum & Bass Mix)",
    year: '',
  },
  {
    id: 56,
    url: 'https://www.youtube.com/watch?v=pl7Xrq3DVoY',
    title: 'Stretch & Vern - Get Up Go Insane (Rock N Roll Mix)',
    year: '1997',
  },
  {
    id: 57,
    url: 'https://www.youtube.com/watch?v=6yikNhPh9n8',
    title: 'Ida Corr - Let Me Think About It (Fedde Le Grand Remix)',
    year: '2007',
  },
  {
    id: 58,
    url: 'https://www.youtube.com/watch?v=_DWWFKYgLw8',
    title: 'Wamdue Project - King Of My Castle (Armin Van Buuren Vocal Remix)',
    year: '1998',
  },
  {
    id: 59,
    url: 'https://www.youtube.com/watch?v=aUMHxHBu8z4',
    title: "Azzido Da Bass - Doom's Night (Stanton Warriors Main Mix)",
    year: '2000',
  },
  {
    id: 60,
    url: 'https://www.youtube.com/watch?v=FgsddjuPjwo',
    title: 'Shakedown - At Night (Kid Creme Remix)',
    year: '2002',
  },
  {
    id: 61,
    url: 'https://www.youtube.com/watch?v=Rn0nc8sAIMY',
    title:
      "Madison Avenue - Don't Call Me Baby (Madison Babe From Outta Space Remix)",
    year: '1999',
  },
  {
    id: 62,
    url: 'https://www.youtube.com/watch?v=OhgHv_2OqGE',
    title: 'Medina - You & I (Deadmau5 Remix)',
    year: '2009',
  },
  {
    id: 63,
    url: 'https://www.youtube.com/watch?v=Oiwcwhn06Fc',
    title: 'Naughty By Nature - O.P.P. (Sunny Days Remix)',
    year: '1991',
  },
  {
    id: 64,
    url: 'https://www.youtube.com/watch?v=1Y6N6hYizmI',
    title: 'Bell Biv Devoe - Do Me (Smooth Remix)',
    year: '1991',
  },
  {
    id: 65,
    url: 'https://www.youtube.com/watch?v=6muf7yAk9Hg',
    title: 'Naughty By Nature - Written On Ya Kitten (QDIII Remix)',
    year: '1994',
  },
  {
    id: 66,
    url: 'https://www.youtube.com/watch?v=gHv0yLis-W8',
    title: 'Supercat - Ghetto Red Hot (Bobby Konders Hip Hop Mix)',
    year: '1992',
  },
  {
    id: 67,
    url: 'https://www.youtube.com/watch?v=WyHyUsCGX20',
    title: "LL Cool J - The Boomin' System (The Underground Mix)",
    year: '1990',
  },
  {
    id: 68,
    url: 'https://www.youtube.com/watch?v=Eg2mF0gKtYw',
    title: 'The Fugees - Nappy Heads (Salaam Remi Remix)',
    year: '1994',
  },
  {
    id: 69,
    url: 'https://www.youtube.com/watch?v=H53wAG01ZNc',
    title: 'Kris Kross - Warm It Up (Butcher Mix)',
    year: '1992',
  },
  {
    id: 70,
    url: 'https://www.youtube.com/watch?v=XnLMt3F6gBs',
    title: 'Jamiroquai - Space Cowboy (David Morales Classic Club Mix)',
    year: '1994',
  },
  {
    id: 71,
    url: 'https://www.youtube.com/watch?v=arWPD83LXWM',
    title: 'Blaque - 808 (Remix)',
    year: '1999',
  },
  {
    id: 72,
    url: 'https://www.youtube.com/watch?v=1MeRhJc0BFs',
    title:
      "The Jungle Brothers - I'll House You (Richie Rich Gee Street Reconstruction Mix)",
    year: '1988',
  },
  {
    id: 73,
    url: 'https://www.youtube.com/watch?v=G9hEEa3NzDU',
    title: 'Keane - Is It Any Wonder? (Tall Paul Remix)',
    year: '2006',
  },
  {
    id: 74,
    url: 'https://www.youtube.com/watch?v=abXyYFYtgXE',
    title: 'Johnny Cash - I Walk The Line (Laurent Wolf Remix)',
    year: '2010',
  },
  {
    id: 75,
    url: 'https://www.youtube.com/watch?v=mx0Xy8jta6o',
    title: 'Bloc Party - Banquet (Phones Disco Edit)',
    year: '2005',
  },
  {
    id: 76,
    url: 'https://www.youtube.com/watch?v=auNTHL_LMfA',
    title: 'The Chemical Brothers - Chemical Beats (Dave Clarke Remix)',
    year: '1995',
  },
  {
    id: 77,
    url: 'https://www.youtube.com/watch?v=pI26WU_cT0A',
    title:
      'Johnny Gill (feat CL Smooth) - Rub You The Right Way (Pete Rock Remix)',
    year: '1990',
  },
  {
    id: 78,
    url: 'https://www.youtube.com/watch?v=zW2SBEqyWTQ',
    title: "New Order - Fine Time (Steve 'Silk' Hurley Remix)",
    year: '1989',
  },
  {
    id: 79,
    url: 'https://www.youtube.com/watch?v=eaWPjPKiWjA',
    title: "Rihanna - Don't Stop The Music (Jody Den Broeder Big Room Edit)",
    year: '2007',
  },
  {
    id: 80,
    url: 'https://www.youtube.com/watch?v=ucgbIEl6YPg',
    title: 'Beck - Ghettochip Malfunction (Hell Yes) (8-bit Remix)',
    year: '2005',
  },
  {
    id: 81,
    url: 'https://www.youtube.com/watch?v=MQEm1aDLa_s',
    title: 'Yeah Yeah Yeahs - Gold Lion (Nick Remix)',
    year: '2006',
  },
  {
    id: 82,
    url: 'https://www.youtube.com/watch?v=DRDHglf7Gd8',
    title: 'Lily Allen - Smile (Gutter Remix)',
    year: '2006',
  },
  {
    id: 83,
    url: 'https://www.youtube.com/watch?v=dfqsaBD6cLE',
    title: 'Sia - Breathe Me (Mylo Remix)',
    year: '2006',
  },
  {
    id: 84,
    url: 'https://www.youtube.com/watch?v=AQ_eEfmtVC0',
    title: 'Sneaker Pimps - Six Underground (Umbrellas Of Ladywell Mix #2)',
    year: '1997',
  },
  {
    id: 85,
    url: 'https://www.youtube.com/watch?v=P6U0ZIvf5iE',
    title:
      'Shabba Ranks (feat Maxi Priest) - Housecall (David Morales 12 Inch Remix)',
    year: '1992',
  },
  {
    id: 86,
    url: 'https://www.youtube.com/watch?v=hzHr_u9F0rM',
    title: 'George Michael - Monkey (Jam & Lewis Remix)',
    year: '1988',
  },
  {
    id: 87,
    url: 'https://www.youtube.com/watch?v=QLrRIo26tLY',
    title: 'Marlena Shaw - California Soul (Diplo Remix)',
    year: '2008',
  },
  {
    id: 88,
    url: 'https://www.youtube.com/watch?v=oO3CNIy3gcM',
    title: 'The Ones - Flawless (ATFC Remix)',
    year: '2001',
  },
  {
    id: 89,
    url: 'https://www.youtube.com/watch?v=uhYnapk6BDM',
    title: 'Urbanized (feat Silvano) - Helpeless (The Kenlou Remix)',
    year: '1992',
  },
  {
    id: 90,
    url: 'https://www.youtube.com/watch?v=0FbV6zZOA30',
    title:
      "Aaron Smith (feat Luvli) - Dancin' (JJ Flores & Steve Smooth Remix)",
    year: '2004',
  },
  {
    id: 91,
    url: 'https://www.youtube.com/watch?v=l8cbzERFuBo',
    title: 'A Tribe Called Quest - Bonita Applebum (Hootie Mix)',
    year: '1990',
  },
  {
    id: 92,
    url: 'https://www.youtube.com/watch?v=HtGLi49hkEw',
    title: "Glenn Lewis - Don't You Forget It (DJ Clue Remix)",
    year: '2001',
  },
  {
    id: 93,
    url: 'https://www.youtube.com/watch?v=GEeim9Ty1Q4',
    title: 'Sade - By Your Side (Ben Watt Lazy Dog Remix)',
    year: '2000',
  },
  {
    id: 94,
    url: 'https://www.youtube.com/watch?v=bb-PLYQRJkw',
    title: 'New Order - Bizarre Love Triangle (Shep Pettibone 12" Remix)',
    year: '1987',
  },
  {
    id: 95,
    url: 'https://www.youtube.com/watch?v=BYyfXdZuI-c',
    title: 'Information Society - Walking Away (Space Age Mix)',
    year: '1988',
  },
  {
    id: 96,
    url: 'https://www.youtube.com/watch?v=pOVDUuF_IlQ',
    title: "Dada Life - Let's Get Bleeped Tonight (Tiesto Remix)",
    year: '2009',
  },
  {
    id: 97,
    url: 'https://www.youtube.com/watch?v=25vVcW1YV94',
    title: '2 Bad Mice - Bomb Scare (1994 Remix)',
    year: '1994',
  },
  {
    id: 98,
    url: 'https://www.youtube.com/watch?v=24vupzM2g2E',
    title: '112 - Anywhere (Emperor Searcy Remix)',
    year: '1999',
  },
  {
    id: 99,
    url: 'https://www.youtube.com/watch?v=Lcp8_1Ef_Og',
    title: 'Outkast - Elevators (ONP 86 Mix)',
    year: '1996',
  },
  {
    id: 100,
    url: 'https://www.youtube.com/watch?v=07OqqFK6_FU',
    title: 'Dru Hill (feat JD & Da Brat) - In My Bed (So So Def Remix)',
    year: '1997',
  },
  {
    id: 101,
    url: 'https://www.youtube.com/watch?v=yuRuWvN0RzE',
    title:
      'Refugee Camp All-Stars (feat Lauryn Hill) - The Sweetest Thing (Mahogany Mix)',
    year: '1997',
  },
  {
    id: 102,
    url: 'https://www.youtube.com/watch?v=ADWPxypmhOY',
    title:
      'Future Sound Of London - We Have Explosive (Mantronik Plastic Formula #1)',
    year: '1997',
  },
  {
    id: 103,
    url: 'https://www.youtube.com/watch?v=J9M7zIB4v-0',
    title: 'Cassius - Feeling For You (Les Rhythmes Digitales Dreamix',
    year: '1999',
  },
  {
    id: 104,
    url: 'https://www.youtube.com/watch?v=9oeOD60J7Bc',
    title: 'Cirrus - Back On A Mission (DJ Dan Remix)',
    year: '1998',
  },
  {
    id: 105,
    url: 'https://www.youtube.com/watch?v=-GJPVQ8OajI',
    title: 'EPMD vs Mantronik - Strictly Business (MBA Remix Edit)',
    year: '1998',
  },
  {
    id: 106,
    url: 'https://www.youtube.com/watch?v=c1yiamSrsto',
    title: "Simply Red - Stars (PM Dawn's Comprende Mix)",
    year: '1991',
  },
  {
    id: 107,
    url: 'https://www.youtube.com/watch?v=84fhnHhmHTc',
    title: "Sublime (feat The Pharcyde) - Doin' Time (Marshall Arts Remix)",
    year: '1997',
  },
  {
    id: 108,
    url: 'https://www.youtube.com/watch?v=oVkatTa0D4c',
    title: 'Gorillaz - 19-2000 (Soulchild Remix)',
    year: '2001',
  },
  {
    id: 109,
    url: 'https://www.youtube.com/watch?v=NHy5J8rBsrA',
    title: 'Chili Hi Fly - Is It Love? (Original 12" Mix)',
    year: '1998',
  },
  {
    id: 110,
    url: 'https://www.youtube.com/watch?v=nygK0pqUmD8',
    title: 'Daft Punk - Harder Better Faster Stronger (The Neptunes Remix)',
    year: '2003',
  },
  {
    id: 111,
    url: 'https://www.youtube.com/watch?v=RIzbOHajEO0',
    title: "Will To Power - Dreamin' (Manhattan Mix)",
    year: '1987',
  },
  {
    id: 112,
    url: 'https://www.youtube.com/watch?v=ZOlTaHfZoN4',
    title: "House Of Pain - Jump Around (Pete Rock Remix)",
    year: '1992',
  },
  {
    id: 113,
    url: 'https://www.youtube.com/watch?v=Mn4xuScGedc',
    title: "The Beastie Boys - Ch-Check It Out (Just Blaze Remix)",
    year: '2004',
  },
  {
    id: 114,
    url: 'https://www.youtube.com/watch?v=8dlnbrLS73o',
    title: "DHS - House Of God (Jack Dangers Mix)",
    year: '2001',
  },
  {
    id: 115,
    url: 'https://www.youtube.com/watch?v=6aP8tJ4xw_Y',
    title: "Alicia Keys - Karma (Karmastition Mix)",
    year: '2004',
  },
  {
    id: 116,
    url: 'https://www.youtube.com/watch?v=ZsZyeZU8TTY',
    title: "Blackstreet - No Diggity (Billie Jean Remix)",
    year: '1996',
  },
  {
    id: 117,
    url: 'https://www.youtube.com/watch?v=4qHTxS6kUxI',
    title: "Kid Cudi - Day & Nite (Crookers Remix)",
    year: '2009',
  },
  {
    id: 118,
    url: 'https://www.youtube.com/watch?v=VUmes8eUZ48',
    title: "The Cure - Close To Me (Closer Mix)",
    year: '1990',
  },
  {
    id: 119,
    url: 'https://www.youtube.com/watch?v=N32zUKUmKr4',
    title: "Lustral - Everytime (Way Out West Sunrise Mix)",
    year: '1999',
  },
  {
    id: 120,
    url: 'https://www.youtube.com/watch?v=lCFx6hytk-Y',
    title: "Dread Flimstone - From The Ghetto (Freddy's Bronx Mix)",
    year: '1992',
  },
  {
    id: 121,
    url: 'https://www.youtube.com/watch?v=1UqQvgk4AKg',
    title: "Bodyrox - Yeah Yeah (D Ramirez Vocal Club Mix)",
    year: '2007',
  },
  {
    id: 122,
    url: 'https://www.youtube.com/watch?v=TFK9l_CaIvk',
    title: "The Movement - Jump! (Funky Hipno Mix)",
    year: '1992',
  },
  {
    id: 123,
    url: 'https://www.youtube.com/watch?v=o7H5ny00OQA&t=72s',
    title: "L.A. Style - James Brown Is Dead (Crossover Mix)",
    year: '1992',
  },
  {
    id: 124,
    url: 'https://www.youtube.com/watch?v=tvN5knh2pI8',
    title: "De La Soul - Say No Go (No Dope Mix)",
    year: '1989',
  },
  {
    id: 125,
    url: 'https://www.youtube.com/watch?v=bHe8Q92Pkhw',
    title: "De La Soul - Me Myself & I (Oblapos Mode)",
    year: '1989',
  },
  {
    id: 126,
    url: 'https://www.youtube.com/watch?v=eTPRM2nWrtQ',
    title: "Sarah McLachlan - Possession (Rabbit In The Moon Remix)",
    year: '1995',
  },
  {
    id: 127,
    url: '',
    title: "",
    year: '',
  },
  {
    id: '',
    url: '',
    title: "",
    year: '',
  },
  {
    id: '',
    url: '',
    title: "",
    year: '',
  },
  {
    id: '',
    url: '',
    title: "",
    year: '',
  },
]

module.exports = twitterContent
