let twitterContent = [
  {
    id: 1,
    url: 'https://www.youtube.com/watch?v=XHHtNFaNCJo',
    title: 'Imagination - Instinctual (David Morales Remix)',
    year: '1987',
  },
  {
    id: 2,
    url: 'https://www.youtube.com/watch?v=jvB4_T_GDNs',
    title: 'Wee Papa Girl Rappers - Heat It Up (Kevin Sanderson Remix)',
    year: '1988',
  },
  {
    id: 3,
    url: 'https://www.youtube.com/watch?v=vDBeSszh8Ok',
    title: 'Eric B & Rakim - Paid In Full (The Coldcut Remix)',
    year: '1987',
  },
  {
    id: 4,
    url: 'https://www.youtube.com/watch?v=zKFRiSUtK-I',
    title: 'George Michael - Hard Day (Shep Pettibone Remix)',
    year: '1987',
  },
  {
    id: 5,
    url: 'https://www.youtube.com/watch?v=WAN8f6583pg',
    title: 'Bjork - Human Behavior (Close To Human Mix)',
    year: '1993',
  },
  {
    id: 6,
    url: 'https://www.youtube.com/watch?v=5vkRMxjvEx0',
    title: "Crystal Method - Comin' Back (Club 69's Future Mix)",
    year: '1998',
  },
  {
    id: 7,
    url: 'https://www.youtube.com/watch?v=5yNZDHCwjdc',
    title: "Garbage - When I Grow Up (Danny Tenaglia's Club Mix)",
    year: '1999',
  },
  {
    id: 8,
    url: 'https://www.youtube.com/watch?v=JJFX5DzK8x0',
    title: 'Underworld - Two Months Off (King Unique Sunspots Vocal Mix)',
    year: '2002',
  },
  {
    id: 9,
    url: 'https://www.youtube.com/watch?v=SFSl91tG5Xo',
    title: 'Filter - Hey Man Nice Shot (1/4 lb Mix)',
    year: '1995',
  },
  {
    id: 10,
    url: 'https://www.youtube.com/watch?v=tqREpyLEsn8',
    title: 'Orgy - Stitches (Cracker Mix)',
    year: '1999',
  },
  {
    id: 11,
    url: 'https://www.youtube.com/watch?v=aOFRaQ3i8qs',
    title: 'Devo - Whip It (Philip Steir Remix)',
    year: '2003',
  },
  {
    id: 12,
    url: 'https://www.youtube.com/watch?v=bOX9tvn-6JI',
    title: "The Pharcyde - Passin' Me By (Fly As Pie Mix)",
    year: '1993',
  },
  {
    id: 13,
    url: 'https://www.youtube.com/watch?v=9lB1jiv83Q0',
    title: '3rd Bass - Wordz Of Wisdom (aka III The Hardway) (Club Mix)',
    year: '1989',
  },
  {
    id: 14,
    url: 'https://www.youtube.com/watch?v=s8G5LMmLhDA',
    title: 'LL Cool J - Mama Said Knock You Out (Hot Mix - Long)',
    year: '1991',
  },
  {
    id: 15,
    url: 'https://www.youtube.com/watch?v=7LnTSV5Oe50',
    title: "Ziggy Marley & The Melody Makers - Tumblin' Down (12 Inch Remix)",
    year: '1988',
  },
  {
    id: 16,
    url: 'https://www.youtube.com/watch?v=JfKmREVDoEc',
    title: 'Peter Gabriel - Steam (Hank Shocklee & The Bomb Squad Remix)',
    year: '1992',
  },
  {
    id: 17,
    url: 'https://www.youtube.com/watch?v=bY9yhgTDP4k',
    title: 'M - Pop Muzik (Ben Liebrand Remix)',
    year: '1989',
  },
  {
    id: 18,
    url: 'https://www.youtube.com/watch?v=DI7bBHB5ZMs',
    title: 'Smashing Pumpkins - 1979 (Roli Mossiman Vocal Mix)',
    year: '1995',
  },
  {
    id: 19,
    url: 'https://www.youtube.com/watch?v=bzT0G8fOI30',
    title: 'Electronic - Disappointed (808 State Remix)',
    year: '1992',
  },
  {
    id: 20,
    url: 'https://www.youtube.com/watch?v=5rRgjvna7bk',
    title: 'Sarah McLachlan - Fear (Lunasol Remix)',
    year: '1993',
  },
  {
    id: 21,
    url: 'https://www.youtube.com/watch?v=COIl5IzVdYg',
    title: 'Portishead - Sour Times (Lot More Mix)',
    year: '1994',
  },
  {
    id: 22,
    url: 'https://www.youtube.com/watch?v=wxiZ0bDPEHM',
    title: 'Lily Allen - LDN (Warbox Remix)',
    year: '2006',
  },
  {
    id: 23,
    url: 'https://www.youtube.com/watch?v=qFaR6rV0DBU',
    title: 'Twin Hype - For Those Who Like To Groove (Club Groove Remix)',
    year: '1989',
  },
  {
    id: 24,
    url: 'https://www.youtube.com/watch?v=dceorz43MwY',
    title: 'Black Moon - I Got Cha Opin (Remix)',
    year: '1994',
  },
  {
    id: 25,
    url: 'https://www.youtube.com/watch?v=abJeoBXixsk',
    title:
      "Method Man (feat Mary J Blige) - I'll Be There For You (Puff Daddy Remix)",
    year: '1995',
  },
  {
    id: 26,
    url: 'https://www.youtube.com/watch?v=GaFRCU3lbik',
    title: 'Roger Sanchez - Turn On The Music (Axwell Remix)',
    year: '2005',
  },
  {
    id: 27,
    url: 'https://www.youtube.com/watch?v=KE2_WFoRHZk',
    title: 'Korn - A.D.I.D.A.S. (Under Pressure Mix)',
    year: '1997',
  },
  {
    id: 28,
    url: 'https://www.youtube.com/watch?v=7Bs8ZskPe3c',
    title: 'P.O.D. - Boom (Crystal Method Remix)',
    year: '2002',
  },
  {
    id: 29,
    url: 'https://www.youtube.com/watch?v=gYJJ-4dQnqw',
    title: 'Deftones - My Own Summer (Shove It) (Charlie Clouser Remix)',
    year: '1999',
  },
  {
    id: 30,
    url: 'https://www.youtube.com/watch?v=wHGTApGNwmo',
    title: 'Hayden James - Something About You (Gazzo Remix)',
    year: '2014',
  },
  {
    id: 31,
    url: 'https://www.youtube.com/watch?v=Tm2y-0a-p8s',
    title:
      'Wanklemut & Emma Louise - My Head Is A Jungle (Friend Within Remix)',
    year: '2014',
  },
  {
    id: 32,
    url: 'https://www.youtube.com/watch?v=zwubKSxpczg',
    title: "The Latin Project - Lei Lo Lai (MAW Mix B's Re-Edit)",
    year: '2003',
  },
  {
    id: 33,
    url: 'https://www.youtube.com/watch?v=QDR8GxDGq0w',
    title: 'EMF - Unbelievable (Hip Hop Mix)',
    year: '1991',
  },
  {
    id: 34,
    url: 'https://www.youtube.com/watch?v=e4PT-FSNLwY',
    title: 'Crazy Town - Butterfly (Epic Remix)',
    year: '2000',
  },
  {
    id: 35,
    url: 'https://www.youtube.com/watch?v=MZnO54HHshs',
    title: "P Diddy & The Family - Victory (Nine Inch Nails Remix)",
    year: '1997',
  },
  {
    id: 36,
    url: 'https://www.youtube.com/watch?v=NYK7mQMnX4Y',
    title: "69 Boyz - Tootsee Roll (Set It Off Mix)",
    year: '1994',
  },
  {
    id: 37,
    url: 'https://www.youtube.com/watch?v=A5QeSl0czW0',
    title: "C.C.C.P. - American Soviets (Cameron Paul Remix)",
    year: '1987',
  },
  {
    id: 38,
    url: 'https://www.youtube.com/watch?v=qMaYmhf87JY',
    title: "N.E.R.D. - Lapdance (Nine Inch Nails Remix)",
    year: '',
  },
  {
    id: 39,
    url: 'https://www.youtube.com/watch?v=8n4l7UdPXIs',
    title: "Leftfield - Dusted (Si Begg's Buckfunk 3000 Remix)",
    year: '1999',
  },
  {
    id: 40,
    url: 'https://www.youtube.com/watch?v=41kXJLheSrc',
    title: "The Prodigy - Voodoo People (Chemical Brothers Remix)",
    year: '1994',
  },
  {
    id: 41,
    url: 'https://www.youtube.com/watch?v=KWHc7rSv03Q',
    title: "The Prodigy - Everybody In The Place (Moby's Dance Hall Version)",
    year: '1992',
  },
  {
    id: 42,
    url: 'https://www.youtube.com/watch?v=Ke0RcBMDjA4',
    title: "808 State - Cubik (Kings County Perspective)",
    year: '1991',
  },
  {
    id: 43,
    url: 'https://www.youtube.com/watch?v=2ZmaJzKEJdo',
    title: "Georgio - Lover's Lane (Club Mix)",
    year: '1987',
  },
  {
    id: 44,
    url: 'https://www.youtube.com/watch?v=gJC1o35b9_s',
    title: "INXS - Guns In The Sky (Kick Ass Remix)",
    year: '1988',
  },
  {
    id: 45,
    url: 'https://www.youtube.com/watch?v=eM5DWw3J4BI',
    title: "Eiffel 65 - Blue (Flume Remix)",
    year: '2020',
  },
  {
    id: 46,
    url: 'https://www.youtube.com/watch?v=xYi_tbr9MMg',
    title: "Jaydee - Plastic Dreams (David Morales Remix)",
    year: '1997',
  },
  {
    id: 47,
    url: 'https://www.youtube.com/watch?v=o2B8y5rsVSM',
    title: "Funky Green Dogs - Fired Up (Angel Moraes ddddDeep Vocal Mix",
    year: '1996',
  },
  {
    id: 48,
    url: 'https://www.youtube.com/watch?v=4eNauLHc7Ls',
    title: "People Underground - Music Is Pumping (Green Street Session Mix)",
    year: '1997',
  },
  {
    id: 49,
    url: 'https://www.youtube.com/watch?v=NuhJP3h31mI',
    title: "Ella Eyre - Deeper (Friend Within Remix)",
    year: '2013',
  },
  {
    id: 50,
    url: 'https://www.youtube.com/watch?v=a0BkP5HDWj0',
    title: "Cornershop - Brimful Of Asha (Fatboy Slim Remix)",
    year: '1997',
  },
]

module.exports = twitterContent
